# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://thinson.github.io/"
title = "Kang's BlogğŸ’»"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
paginate = 5              # Number of articles displayed on the homepage  # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
rssLimit = 20             # Limit Entry Count to Rss file # é™åˆ¶ Rss æ–‡ç« è¾“å‡ºæ•°é‡
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name â†“        # é»˜è®¤ä¸ºä¸‹é¢é…ç½®çš„author.name â†“

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"


# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use
[languages.en]
  languageCode = "en"
[languages.zh-cn]
  languageCode = "zh-cn"

[author]                  # essential                     # å¿…éœ€
  name = "kang"

[sitemap]                 # essential                     # å¿…éœ€
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # é…ç½®ç›®å½•
  name = "ä¸»é¡µ"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "å½’æ¡£"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "æ ‡ç­¾"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "åˆ†ç±»"
  weight = 40
  identifier = "categories"
  url = "/categories/"
# [[menu.main]]
#   name = "external-link"
#   weight = 50
#   url = "https://gohugo.io"


[params]
  since = "2022"            # Site creation time          # ç«™ç‚¹å»ºç«‹æ—¶é—´
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # ç«™ç‚¹ä¿¡æ¯ï¼ˆå¯é€‰ï¼Œä¸éœ€è¦çš„å¯ä»¥ç›´æ¥æ³¨é‡Šæ‰ï¼‰
  logoTitle = "Kang"        # default: the title value    # é»˜è®¤å€¼: ä¸Šé¢è®¾ç½®çš„titleå€¼
  keywords = ["ç”Ÿæ´»", "å­¦æœ¯", "æŠ€æœ¯"]
  description = "This is the blog for Kang."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # ä¸€äº›å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½ï¼Œåœ¨ archetypes/default.md æŸ¥çœ‹æ›´å¤šä¿¡æ¯ã€‚
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # æ˜¯å¦å¼€å¯ç›®å½•
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # æ˜¯å¦å¯ç”¨PhotoSwipeï¼ˆå›¾ç‰‡å¯ç‚¹å‡»ï¼‰
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social]                                         # ç¤¾äº¤é“¾æ¥
    a-email = "mailto:kang_wu@foxmail.com"
    # b-stack-overflow = "http://localhost:1313"
    #c-twitter = "http://localhost:1313"
    #d-facebook = "http://localhost:1313"
    #e-linkedin = "http://localhost:1313"
    #f-google = "http://localhost:1313"
    g-github = "https://github.com/thinson"
    #h-weibo = "http://localhost:1313"
    #i-zhihu = "http://localhost:1313"
    #j-douban = "http://localhost:1313"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "http://localhost:1313"
    #n-gitlab = "http://localhost:1313"
    #o-goodreads = "http://localhost:1313"
    #p-coding = "http://localhost:1313"
    #q-bilibili = "http://localhost:1313"
    #r-codeforces = "http://localhost:1313"
    #s-mastodon = "http://localhost:1313"
    #t-youtube = "http://localhost:1313"
    #u-twitch = "http://localhost:1313"

[markup]
  defaultMarkdownHandler = "goldmark"  # blackfriday or goldmark
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true